Doc/dashboard deploy
ufcg-lsd/saps-dashboard pull request #14
Opened 2020-03-23 12:50 UTC by thiagoyeds

2020-03-23 22:57 UTC, thiagomanel commented on README.md
> +- [SAPS Dispatcher Service URL](/public/dashboardApp.js) allows the communication with the SAPS dispatcher. Assing the dispatcher address (```http://$dispatcher_access_ip:$dispatcher_access_port/```)
not sure it is a matter of documentation only but also a matter of changing the code but is bad having different names for the same thing. For example, why we have both `dispatcher_access_port` and `submission_rest_server_port`? Shouldn't we use `dispatcher_access_port` in both places?

2020-03-23 22:58 UTC, thiagomanel requested changes
Thanks, @thiagoyeds. I've have made some direct commits to improve the documentation. I've also added a small request (note that, it is not a request to change the code, necessarily. I'm ok with an explanation).

2020-03-24 11:34 UTC, thiagoyeds commented on README.md
> +- [SAPS Dispatcher Service URL](/public/dashboardApp.js) allows the communication with the SAPS dispatcher. Assing the dispatcher address (```http://$dispatcher_access_ip:$dispatcher_access_port/```)
Yes, this is really bad, but it is something that already existed, what do you suggest? I can change it to ```http://$submission_rest_server_ip:$submission_rest_server_port/```

2020-03-24 11:47 UTC, thiagomanel commented on README.md
> +- [SAPS Dispatcher Service URL](/public/dashboardApp.js) allows the communication with the SAPS dispatcher. Assing the dispatcher address (```http://$dispatcher_access_ip:$dispatcher_access_port/```)
bad. isn't clearer to user `http://$dispatcher_access_ip:$dispatcher_access_port/`?

2020-03-24 11:52 UTC, thiagoyeds commented on README.md
> +- [SAPS Dispatcher Service URL](/public/dashboardApp.js) allows the communication with the SAPS dispatcher. Assing the dispatcher address (```http://$dispatcher_access_ip:$dispatcher_access_port/```)
Yes, I will create an issue in the saps-engine repository about changing this name to ```dispatcher_access_port```

2020-03-24 11:55 UTC, merged