Fixed single quotes of awk command
ufcg-lsd/saps-dashboard pull request #17
Opened 2020-04-13 14:40 UTC by wesleymonte

Resolves #15

2020-05-04 15:37 UTC, raonismaneoto requested changes
can we trust in this script? I'm afraid that this grep command may cause some unexpected behavior, app.js is very common. You can search the PID by using `lsof -i :port | awk '{ print $2}'`, the port is the port where the application is running. If u have some time try it out and check if it works

2020-05-05 13:30 UTC, raonismaneoto requested changes

2020-05-05 13:30 UTC, raonismaneoto commented on bin/stop-dashboard
> +echo "Run as Sudo!"
as root* or with sudo

2020-05-05 19:56 UTC, wesleymonte commented on bin/stop-dashboard
> +echo "Run as Sudo!"
Done.

2020-05-05 19:57 UTC, raonismaneoto approved these changes

2020-10-29 20:58 UTC, thiagomanel commented on bin/stop-dashboard
> +echo "Run as root!"
remove this echo. add as comment

2020-10-29 21:00 UTC, thiagomanel commented on bin/stop-dashboard
> +if [ -z $PID ]; then
change line 10 to `echo "PID" ${PID} "not found"

2020-10-29 21:01 UTC, thiagomanel requested changes
one request to remove a line and another to improve echo

2020-10-30 02:21 UTC, wesleymonte commented on bin/stop-dashboard
> +echo "Run as root!"
Done.

2020-10-30 02:21 UTC, wesleymonte commented on bin/stop-dashboard
> +if [ -z $PID ]; then
Done.

2020-10-31 13:03 UTC, joivo approved these changes

2020-11-09 16:51 UTC, thiagomanel approved these changes
lgtm

2020-11-09 16:51 UTC, merged